// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingcustomerinfofktousers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingcustomerinfofktousers));
        
        string IMigrationMetadata.Id
        {
            get { return "201807301432186_adding customer info fk to users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
